

export const secrets = [
    { site: "Atm pin", username: "Pin", password: "1234" },
    { site: "Email", username: "example@gmail.com", password: "password123" },
    { site: "Social Media", username: "john_doe", password: "abcd@1234" },
    { site: "Bank Account", username: "account123", password: "securepass1" },
    { site: "Netflix", username: "user_netflix", password: "streaming2023" },
    { site: "Amazon", username: "shopper01", password: "buybuy2023" },
    { site: "GitHub", username: "coder123", password: "gitpassword" },
    { site: "Facebook", username: "fb_user", password: "likeandshare" },
    { site: "Twitter", username: "tweet_user", password: "birdsong" },
    { site: "Instagram", username: "insta_lover", password: "picturethis" },
    { site: "LinkedIn", username: "pro_networker", password: "career2024" },
    { site: "Spotify", username: "music_addict", password: "playlist" },
    { site: "Dropbox", username: "cloud_user", password: "storagesafe" },
    { site: "Reddit", username: "redditfan", password: "postandvote" },
    { site: "YouTube", username: "videolover", password: "watchtime" },
    { site: "PayPal", username: "payment_user", password: "securepay" },
    { site: "Uber", username: "driver_user", password: "rideeasy" },
    { site: "Zomato", username: "foodie123", password: "hungrynow" },
    { site: "Swiggy", username: "fastfoodie", password: "deliverfast" },
    { site: "Flipkart", username: "shopaddict", password: "indianshopping" },
    { site: "Snapchat", username: "snapster", password: "ghostmode" },
    { site: "WhatsApp", username: "chatlover", password: "messaging" },
    { site: "Telegram", username: "secretchatter", password: "encrypted" },
    { site: "Zoom", username: "meetings", password: "confer123" },
    { site: "Slack", username: "workspace_user", password: "collabtool" },
    { site: "Microsoft", username: "msuser", password: "office365" },
    { site: "Google", username: "gmail_user", password: "googling" },
    { site: "Apple", username: "icloud_user", password: "applesecrets" },
    { site: "Quora", username: "questions", password: "answers123" },
    { site: "Pinterest", username: "pinlover", password: "boardideas" },
    { site: "TikTok", username: "shortvideo", password: "dancemove" },
    { site: "Discord", username: "serverfan", password: "gaming123" },
    { site: "Twitch", username: "streamer", password: "gametime" },
    { site: "Adobe", username: "photoshop", password: "creativity" },
    { site: "Coursera", username: "learner", password: "studytime" },
    { site: "Udemy", username: "course_user", password: "skills2024" },
    { site: "Khan Academy", username: "student123", password: "mathrules" },
    { site: "Duolingo", username: "language_learner", password: "practice123" },
    { site: "Github Gists", username: "snippet_user", password: "codestore" },
    { site: "Medium", username: "writer", password: "blog123" },
    { site: "Bitbucket", username: "repo_user", password: "bitcode" },
    { site: "Asana", username: "taskmaster", password: "project123" },
    { site: "Trello", username: "board_user", password: "kanban123" },
    { site: "Notion", username: "planner", password: "organization" },
    { site: "Grammarly", username: "writerpro", password: "wordsmith" },
    { site: "Canva", username: "designer", password: "graphics" },
    { site: "Etsy", username: "crafter", password: "handmade2024" },
    { site: "WordPress", username: "blogadmin", password: "webpublish" },
    { site: "Figma", username: "uxdesigner", password: "prototype" },
    { site: "Dribbble", username: "artist", password: "creativeworks" },
];
